name: Bug Report
description: Please enter the details of your bug
body:
  - type: textarea
    attributes:
      label: What is the issue?
      description: Insert a detailed description of what your issue is
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What is the issue with?
      options:
        - CI
        - Effis
        - Todel
        - Pandemonium
        - Oprish
        - CLI

  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: Have you checked the documentation?
          required: true
        - label: Have you checked other issues to make sure this is not a duplicate?
          required: true

  - type: textarea
    attributes:
      label: Minimum Reproducible Sample/Code
      description: Insert any code or steps to help reproduce this issue
    validations:
      required: true
      
