name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  buildx:
    name: Build and Push

    strategy:
      matrix:
        service:
          - oprish
          - pandemonium
          - effis

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=
            type=sha,format=long,prefix=
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'next') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # Multiple packages.
          logout: false

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:latest
          cache-to: type=inline
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
